language: cpp

sudo: false

cache:
  pip: true
  directories:
    - "$HOME/.pip-cache"
    - "$HOME/iris-distro/venv"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - pkg-config
      - libgmp-dev
      - gcc-4.8
      - g++-4.8
      - clang
      - python-numpy
      - python-scipy
      - python-matplotlib
      - python-nose
      - python-virtualenv

compiler:
  - gcc
  - clang

python:
  - '2.7'

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

git:
  submodules: false

before_install:
  - openssl aes-256-cbc -K $encrypted_b279d3ed6718_key -iv $encrypted_b279d3ed6718_iv -in lic.enc -out lic -d
  - mkdir -p $HOME/mosek
  - mv lic $HOME/mosek/mosek.lic
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init
  - sed -i 's/git@github.com:/https:\/\/github.com\//' iris/.gitmodules
  - sed -i 's/git@github.com:/https:\/\/github.com\//' mosek-pod/.gitmodules
  - git submodule update --init --recursive
  - virtualenv --system-site-packages venv
  - source venv/bin/activate
  - pip install --upgrade pip
  - pip install --upgrade distribute
  - pip install cython --cache-dir=$HOME/.pip-cache

script:
  - mkdir build
  - make
  - make test
