language: python

notifications:
  email: false

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      python: "2.7"
    - os: osx
      language: generic

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y cmake pkg-config libgmp-dev swig; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python cmake pkg-config gmp; fi
  - mkdir -p $HOME/.config/matplotlib
  - echo backend\:\ agg >> $HOME/.config/matplotlib/matplotlibrc
  - export MATPLOTLIBRC=$HOME/.config/matplotlib
  - openssl aes-256-cbc -K $encrypted_b279d3ed6718_key -iv $encrypted_b279d3ed6718_iv -in lic.enc -out lic -d
  - mkdir -p $HOME/mosek
  - mv lic $HOME/mosek/mosek.lic
  - pip install -r requirements.txt
  - pip install jupyter

install:
  - mkdir build
  - make

script:
  - source build/config/pods_setup_all.sh
  - CTEST_OUTPUT_ON_FAILURE=1 make test
