language: python

notifications:
  email: false

branches:
  only: 
    - master

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      python: "2.7"
    - os: linux
      sudo: required
      dist: trusty
      python: "3.5"
    - os: osx
      language: generic

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y cmake pkg-config libgmp-dev ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python ; fi
  - mkdir -p $HOME/.config/matplotlib
  - echo backend\:\ agg >> $HOME/.config/matplotlib/matplotlibrc
  - export MATPLOTLIBRC=$HOME/.config/matplotlib
  - openssl aes-256-cbc -K $encrypted_b279d3ed6718_key -iv $encrypted_b279d3ed6718_iv -in lic.enc -out lic -d
  - mkdir -p $HOME/mosek
  - mv lic $HOME/mosek/mosek.lic
  - pip install -r requirements.txt
  - pip install jupyter

install:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_BUILD_TYPE=Release
  - make

script:
  - cd iris_project-prefix/src/iris_project-build
  - ctest --output-on-failure
