language: cpp

sudo: false

cache:
  pip: true
  directories:
    - "$HOME/.pip-cache"
    - "$HOME/build/rdeits/iris-distro/venv"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - pkg-config
      - libgmp-dev
      - gcc-4.8
      - g++-4.8
      - gfortran
      - libblas-dev
      - liblapack-dev
      - clang
      - python-virtualenv

compiler:
  - gcc
  - clang

python:
  - '2.7'

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

git:
  submodules: false

before_install:
  - mkdir -p $HOME/.config/matplotlib
  - echo backend\:\ agg >> $HOME/.config/matplotlib/matplotlibrc
  - export MATPLOTLIBRC=$HOME/.config/matplotlib
  - openssl aes-256-cbc -K $encrypted_b279d3ed6718_key -iv $encrypted_b279d3ed6718_iv -in lic.enc -out lic -d
  - mkdir -p $HOME/mosek
  - mv lic $HOME/mosek/mosek.lic
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init
  - sed -i 's/git@github.com:/https:\/\/github.com\//' iris/.gitmodules
  - git submodule update --init --recursive
  - virtualenv venv
  - source venv/bin/activate
  - pip install --upgrade pip
  - pip install --upgrade distribute --cache-dir=$HOME/.pip-cache
  - pip install --upgrade -r python_requirements.txt --cache-dir=$HOME/.pip-cache

script:
  - mkdir build
  - make
  - source build/config/pods_setup_all.sh
  - source venv/bin/activate
  - CTEST_OUTPUT_ON_FAILURE=1 make test
