sudo: false
addons:
  apt:
    packages:
      - cmake
      - pkg-config
      - libgmp-dev

compiler: gcc

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

git:
  submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init
  - sed -i 's/git@github.com:/https:\/\/github.com\//' iris/.gitmodules
  - sed -i 's/git@github.com:/https:\/\/github.com\//' mosek-pod/.gitmodules
  - git submodule update --init --recursive

script: 
  - mkdir build
  - make

